# Generated by Django 4.2.5 on 2025-07-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUGJournalRanking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=190, verbose_name='FULL_NAME')),
                ('short_name', models.CharField(default='N/A', max_length=100, verbose_name='SHORT_NAME')),
                ('tier', models.CharField(max_length=64, verbose_name='TIER')),
                ('subject', models.CharField(max_length=100, verbose_name='SUBJECT')),
                ('tag', models.CharField(default='', max_length=64, verbose_name='TAG')),
                ('jif21', models.CharField(default='N/A', max_length=64, verbose_name='JIF21')),
                ('jif22', models.CharField(default='N/A', max_length=64, verbose_name='JIF22')),
                ('jif23', models.CharField(default='N/A', max_length=64, verbose_name='JIF23')),
                ('issn', models.CharField(default='N/A', max_length=64, verbose_name='ISSN')),
                ('eissn', models.CharField(default='N/A', max_length=64, verbose_name='EISSN')),
                ('letpub_id', models.BigIntegerField(default=0, verbose_name='LETPUB_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=190, unique=True, verbose_name='FULL_NAME')),
                ('short_name', models.CharField(max_length=100, verbose_name='SHORT_NAME')),
                ('jif21', models.CharField(max_length=64, verbose_name='JIF21')),
                ('jif22', models.CharField(max_length=64, verbose_name='JIF22')),
                ('jif23', models.CharField(max_length=64, verbose_name='JIF23')),
                ('category', models.CharField(max_length=500, verbose_name='CATEGORY')),
                ('issn', models.CharField(max_length=64, verbose_name='ISSN')),
                ('eissn', models.CharField(max_length=64, verbose_name='EISSN')),
                ('letpub_id', models.BigIntegerField(default=0, verbose_name='LETPUB_ID')),
            ],
        ),
    ]
