# Generated by Django 4.2.5 on 2025-07-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cugjournalranking',
            name='jif24',
            field=models.CharField(default='N/A', max_length=64, verbose_name='JIF24'),
        ),
        migrations.AddField(
            model_name='journal',
            name='jif24',
            field=models.CharField(default='N/A', max_length=64, verbose_name='JIF24'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='jif21',
            field=models.CharField(default='N/A', max_length=64, verbose_name='JIF21'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='jif22',
            field=models.CharField(default='N/A', max_length=64, verbose_name='JIF22'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='jif23',
            field=models.CharField(default='N/A', max_length=64, verbose_name='JIF23'),
        ),
    ]
