# Generated by Django 4.2.5 on 2026-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_cugjournalranking_jif24_journal_jif24_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cugjournalranking',
            name='xinrui_id',
            field=models.CharField(default='N/A', max_length=10, verbose_name='XINRUI_ID'),
        ),
        migrations.AddField(
            model_name='journal',
            name='xinrui_id',
            field=models.CharField(default='N/A', max_length=10, verbose_name='XINRUI_ID'),
        ),
    ]
