# Generated by Django 4.2.5 on 2026-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_cugjournalranking_xinrui_id_journal_xinrui_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cugjournalranking',
            name='xinrui_tier',
            field=models.CharField(default='N/A', max_length=10, verbose_name='XINRUI_TIER'),
        ),
        migrations.AddField(
            model_name='cugjournalranking',
            name='xinrui_top',
            field=models.BooleanField(default=False, max_length=10, verbose_name='XINRUI_TOP'),
        ),
        migrations.AddField(
            model_name='journal',
            name='xinrui_tier',
            field=models.CharField(default='N/A', max_length=10, verbose_name='XINRUI_TIER'),
        ),
        migrations.AddField(
            model_name='journal',
            name='xinrui_top',
            field=models.BooleanField(default=False, max_length=10, verbose_name='XINRUI_TOP'),
        ),
    ]
