# Generated by Django 4.2.5 on 2025-07-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_cugjournalranking_eissn_cugjournalranking_issn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cugjournalranking',
            name='letpub_id',
            field=models.BigIntegerField(default=0, verbose_name='LETPUB_ID'),
        ),
        migrations.AddField(
            model_name='journal',
            name='letpub_id',
            field=models.BigIntegerField(default=0, verbose_name='LETPUB_ID'),
        ),
    ]
