# Generated by Django 4.2.5 on 2025-05-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_thermoparams'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBInstruments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=64, verbose_name='IP')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='INSERT_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='NAME')),
                ('uploader_email', models.EmailField(max_length=64, null=True, verbose_name='UPLOADER_EMAIL')),
                ('manufacturer', models.CharField(max_length=32, null=True, verbose_name='MANUFACTURER')),
                ('cup_structure', models.CharField(max_length=32, null=True, verbose_name='CUP_STRUCTURE')),
                ('amplifier', models.CharField(max_length=32, null=True, verbose_name='AMPLIFIER')),
                ('sensitivity', models.CharField(max_length=32, null=True, verbose_name='SENSITIVITY')),
                ('resolution', models.CharField(max_length=32, null=True, verbose_name='RESOLUTION')),
                ('papers', models.CharField(max_length=1000, null=True, verbose_name='PAPERS')),
                ('info', models.CharField(max_length=1000, null=True, verbose_name='INFO')),
            ],
        ),
        migrations.CreateModel(
            name='DBLaboratories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=64, verbose_name='IP')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='INSERT_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='NAME')),
                ('uploader_email', models.EmailField(max_length=64, null=True, verbose_name='UPLOADER_EMAIL')),
                ('country', models.CharField(max_length=32, null=True, verbose_name='COUNTRY')),
                ('city', models.CharField(max_length=32, null=True, verbose_name='CITY')),
                ('manager', models.CharField(max_length=32, null=True, verbose_name='MANAGER')),
                ('instruments', models.CharField(max_length=500, null=True, verbose_name='INSTRUMENTS')),
                ('papers', models.CharField(max_length=1000, null=True, verbose_name='PAPERS')),
                ('info', models.CharField(max_length=1000, null=True, verbose_name='INFO')),
            ],
        ),
        migrations.CreateModel(
            name='DBStandards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=64, verbose_name='IP')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='INSERT_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='NAME')),
                ('uploader_email', models.EmailField(max_length=64, null=True, verbose_name='UPLOADER_EMAIL')),
                ('material', models.CharField(max_length=32, null=True, verbose_name='MATERIAL')),
                ('location', models.CharField(max_length=32, null=True, verbose_name='LOCATION')),
                ('age', models.CharField(max_length=32, null=True, verbose_name='AGE')),
                ('age_error', models.CharField(max_length=32, null=True, verbose_name='AGE_ERROR')),
                ('arp', models.CharField(max_length=32, null=True, verbose_name='ARP')),
                ('arp_error', models.CharField(max_length=32, null=True, verbose_name='ARP_ERROR')),
                ('kp', models.CharField(max_length=32, null=True, verbose_name='KP')),
                ('kp_error', models.CharField(max_length=32, null=True, verbose_name='KP_ERROR')),
                ('arrp', models.CharField(max_length=32, null=True, verbose_name='ARRP')),
                ('arrp_error', models.CharField(max_length=32, null=True, verbose_name='ARRP_Error')),
                ('papers', models.CharField(max_length=1000, null=True, verbose_name='PAPERS')),
                ('info', models.CharField(max_length=1000, null=True, verbose_name='INFO')),
            ],
        ),
    ]
