# Generated by Django 4.2.5 on 2025-12-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_dbinstruments_dblaboratories_dbstandards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedFiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=64, verbose_name='USER_UUID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('file_path', models.CharField(max_length=1000, null=True, verbose_name='FILE_PATH')),
                ('original_name', models.CharField(max_length=1000, null=True, verbose_name='FILE_NAME')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='INSERT_TIME')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UPDATE_TIME')),
            ],
        ),
    ]
