# Generated by Django 4.2.5 on 2025-12-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_receivedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedfiles',
            name='deleted',
            field=models.BooleanField(null=True, verbose_name='DELETED'),
        ),
        migrations.AddField(
            model_name='receivedfiles',
            name='deleted_time',
            field=models.DateTimeField(null=True, verbose_name='DELETED_TIME'),
        ),
    ]
