# Generated by Django 4.2.5 on 2025-12-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_receivedfiles_deleted_receivedfiles_deleted_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcparams',
            name='uploaded_uuid',
            field=models.CharField(max_length=64, null=True, verbose_name='UPLOADER_UUID'),
        ),
        migrations.AddField(
            model_name='exportpdfparams',
            name='uploaded_uuid',
            field=models.CharField(max_length=64, null=True, verbose_name='UPLOADER_UUID'),
        ),
        migrations.AddField(
            model_name='inputfilterparams',
            name='uploaded_uuid',
            field=models.CharField(max_length=64, null=True, verbose_name='UPLOADER_UUID'),
        ),
        migrations.AddField(
            model_name='irraparams',
            name='uploaded_uuid',
            field=models.CharField(max_length=64, null=True, verbose_name='UPLOADER_UUID'),
        ),
        migrations.AddField(
            model_name='smpparams',
            name='uploaded_uuid',
            field=models.CharField(max_length=64, null=True, verbose_name='UPLOADER_UUID'),
        ),
        migrations.AddField(
            model_name='thermoparams',
            name='uploaded_uuid',
            field=models.CharField(max_length=64, null=True, verbose_name='UPLOADER_UUID'),
        ),
    ]
