# Generated by Django 4.2.5 on 2025-12-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_calcparams_uploaded_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calcparams',
            old_name='uploaded_uuid',
            new_name='uploader_uuid',
        ),
        migrations.RenameField(
            model_name='exportpdfparams',
            old_name='uploaded_uuid',
            new_name='uploader_uuid',
        ),
        migrations.RenameField(
            model_name='inputfilterparams',
            old_name='uploaded_uuid',
            new_name='uploader_uuid',
        ),
        migrations.RenameField(
            model_name='irraparams',
            old_name='uploaded_uuid',
            new_name='uploader_uuid',
        ),
        migrations.RenameField(
            model_name='smpparams',
            old_name='uploaded_uuid',
            new_name='uploader_uuid',
        ),
        migrations.RenameField(
            model_name='thermoparams',
            old_name='uploaded_uuid',
            new_name='uploader_uuid',
        ),
    ]
